-- users.sql
GRANT USAGE ON SCHEMA seqdb TO seqdb_webapp;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON ALL TABLES IN SCHEMA seqdb TO seqdb_webapp;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA seqdb TO seqdb_webapp;
ALTER DEFAULT PRIVILEGES IN SCHEMA seqdb GRANT ALL PRIVILEGES ON TABLES TO seqdb_webapp;

CREATE ROLE seqdb_migration NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN PASSWORD 'changeme2';
GRANT CONNECT ON DATABASE seqdb_prod TO seqdb_migration;
GRANT USAGE, CREATE ON SCHEMA seqdb TO seqdb_migration;
ALTER DEFAULT PRIVILEGES IN SCHEMA seqdb GRANT ALL PRIVILEGES ON TABLES TO seqdb_migration;

ALTER DEFAULT PRIVILEGES FOR USER seqdb_migration IN SCHEMA seqdb GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON TABLES TO seqdb_webapp;
ALTER DEFAULT PRIVILEGES FOR USER seqdb_migration IN SCHEMA seqdb GRANT SELECT, USAGE ON SEQUENCES TO seqdb_webapp;
